# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy
run-name: Deploy - ${{inputs.environment}}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment Name
        type: choice
        options:
          - ADT
          - QAT
          - PRD

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUB_ID}}
      ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}

    steps:
      - uses: actions/checkout@v4

      - uses: qetza/replacetokens-action@v1
        with:
          sources: "*.tf"
          variables: '[${{ toJSON(vars) }}, ${{ toJSON(secrets) }}]'
          if-no-files-found: error
          missing-var-log: error
          token-pattern: octopus

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: "1.9.6"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUB_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - run: terraform init
        name: Initialize Terraform

      - run: terraform apply -auto-approve
        name: Apply Terraform

      - name: Setup Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: npm install and build
        run: |
          npm install
        working-directory: src

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: app-svl-${{vars.ENV_NAME}}-${{vars.RESOURCE_GROUP_LOCATION}}
          package: src
