name: Build and Validate
run-name: ${{github.ref_name}}

on:
    push:
        branches:
            - feature/*

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v4
    
          - name: Set up Node.js version
            uses: actions/setup-node@v4
            with:
              node-version: '20.x'
    
          - name: npm install, build, and test
            run: |
              npm install
              npm run build --if-present
              npm run test --if-present

          - name: Install Terraform
            uses: hashicorp/setup-terraform@v3
            with:
                terraform_version: "1.9.6"

          - name: Initialize Terraform
            run: terraform init --backend=false
          
          - name: Validate Terraform
            run: terraform validate
    
          - name: Zip artifact for deployment job
            run: zip release.zip ./* -r
    
          - name: Upload artifact for deployment job
            uses: actions/upload-artifact@v4
            with:
              name: node-app
              path: release.zip