# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy
run-name: Deploy - ${{inputs.environment}}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment Name
        type: choice
        options:
          - ADT
          - QAT
          - PRD

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: "1.9.6"

      - run: terraform init --backend=false
        name: Initialize Terraform

      - run: terraform plan
        name: Plan Terraform

      - name: npm install and build
        run: |
          npm install
          npm run build --if-present

      - name: Zip artifact for deployment job
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - uses: qetza/replacetokens-action@v1
        with:
          sources: variables.tf
          variables: '[${{ toJSON(vars) }}, ${{ toJSON(secrets) }}]'
          if-no-files-found: error
          missing-var-log: error
          token-pattern: octopus

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.6" 

      - run: terraform init
        name: Initialize Terraform

      - run: terraform deploy
        name: Deploy Terraform

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-svl-prod-westus-001'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C6D7D47A32024485B7B0E8CACABDC455 }}
          package: .
