name: Print Secret

on:
    workflow_dispatch

jobs:
    print1:
        runs-on: ubuntu-latest
        name: Print ADT Secret
        environment: ADT

        steps:
            - name: Print ADT
              run: |
                echo ${{secrets.UW_CERT}}

    print2:
        runs-on: ubuntu-latest
        name: Print QAT Secret
        environment: QAT

        steps:
            - name: Print QAT
              run: |
                echo ${{secrets.UW_CERT}}